UPDATE USER, USER_SESSION SET 
USER.STATUS=JSON_REMOVE(USER.STATUS,'$.pfv'), 
USER_SESSION.STATUS=JSON_REMOVE(USER.STATUS,'$.pfv')
WHERE USER.ID=USER_SESSION.USER_ID
AND JSON_CONTAINS(USER.STATUS, JSON_QUOTE(?), '$.pfv');