set @pfv=?;

UPDATE USER SET 
USER.STATUS=JSON_REMOVE(USER.STATUS,'$.pfv')
WHERE JSON_CONTAINS(USER.STATUS, JSON_QUOTE(@pfv), '$.pfv');

UPDATE USER_SESSION SET
USER_SESSION.STATUS=JSON_REMOVE(USER_SESSION.STATUS,'$.pfv')
WHERE JSON_CONTAINS(USER_SESSION.STATUS, JSON_QUOTE(@pfv), '$.pfv');